<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/figures/PDSH-cover-small.png?raw=1">

*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<!--NAVIGATION-->
< [Fancy Indexing](02.07-Fancy-Indexing.ipynb) | [Contents](Index.ipynb) | [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb) >

<a href="https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.08-Sorting.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# 排序陣列(Sorting Arrays)

## 在Numpy中快速排序: ``np.sort`` and ``np.argsort``

要傳回排序過的陣列版本而不更動到原有輸入的內容，可以使用`np.sort`:

In [1]:
import numpy as np

In [2]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

如果想要在陣列中直接進行排序，可以使用陣列的`sort`方法來取代:

In [3]:
x.sort()
print(x)

[1 2 3 4 5]


一個相關的函式是`argsort`, 它被用來傳回被排序過的索引值(位置):

In [4]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


如果想要排序過後的結果，也可以用Fancy索引

In [ ]:
x[i]

array([1, 2, 3, 4, 5])

### 沿著列(rows)或欄(columns)排序

Numpy排序的特色是，可以在多維陣列中用來指定要被排序的列或欄。
只要用`axis`這個參數即可。

In [5]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [6]:
# 對橫軸進行操作，排序X中的每一欄column
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [7]:
# 對縱軸進行操作，排序X中的每一列row
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## 部分排序: 分區(Partitioning)

``np.partition`` 可取得元素第k個值放在最終排序的位置，陣列最小的某幾個值放在左側，剩下的放在右側

In [8]:
x = np.array([7, 2, 3, 1, 6, 5, 4]) # 排序後np.array([1, 2, 3, 4, 5, 6, 7])
np.partition(x, 1)

array([1, 2, 3, 7, 6, 5, 4])

In [13]:
np.partition(x, 4)

array([2, 1, 3, 4, 5, 6, 7])

In [14]:
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [16]:
np.partition(x, 8)

ValueError: ignored