<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/figures/PDSH-cover-small.png?raw=1">

*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<!--NAVIGATION-->
< [Introduction to NumPy](02.00-Introduction-to-NumPy.ipynb) | [Contents](Index.ipynb) | [The Basics of NumPy Arrays](02.02-The-Basics-Of-NumPy-Arrays.ipynb) >

<a href="https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.01-Understanding-Data-Types.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>


# Colab介紹及基本操作解說

## 介紹

1. Google Colaboratory (Colab)是Google由所開發,主要目的是想要幫助機器學習和教育的推廣。
2. 在雲端提供Jupyter Notebook (一種Python開發工具，為套裝編輯器版)的程式撰寫環境，無需額外的設定或下載其他的軟體就可以使用,而且提供免費的GPU及TPU可做加速運算。
3. 預設即安裝了一些常見的機器學習套件，如:Numpy, pandas, matplotlib
4. 適合入門者學習寫code練習用，之後可視自己的需求額外下載其他編輯器(如:Anaconda, Pycharm, VScode等等)
5. 雖說是免費的GPU和TPU，但只要有15分鐘沒有使用或者已經使用超過12小時，系統就會自己斷線不讓你使用GPU和TPU了。

## 基本操作解說

1. 通常我都會轉成英文版本，看起來比較美觀 (說明/查看英文版本)。
2. 一個程式(Code)或文字(text)，都稱為單元(Cell)。
3. 可以在單元與單元間建立程式或文字單元。
4. 執行程式的前置作業:點選右上角的"連線"，出現記憶體(RAM)和磁碟後，代表已經連線到Google的虛擬機器做GPU或TPU加速，可確認目前記憶體和磁碟的使用狀況。
5. 確認現在是否有硬體加速:"執行階段"/"變更執行階段"
6. 執行程式的方式有三種:點選播放紐、Shift + enter (執行後游標在下一個cell)、Control + enter (執行後游標在同一個cell)
7. 結果文字編輯後，可按Shift + enter
7. 可以用#當作書籤做標記(markdown)，如:第一層為#、第二層為##

# 了解Python的資料型態


## Python的list不僅僅只是list

List為一個可修改多元素的容器，建立整數(integer)的list如下所示。

In [ ]:
X = 1
print(X)

1


In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
A = list(range(20))
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [ ]:
type(L[0])

int

建立字串(string)的list如下:

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
type(L2[0])

str

可以建立異質性的list (混合不同屬性的元素)

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

## Python的固定型態陣列(array)

內建的array套件可建立單一型態的稠密陣列:

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'i'是用來設定接下來的內容型態為整數

Numpy套件及Numpy套件中的ndarray可以增加資料操作的效率


In [1]:
import numpy as np

## 從Python list中建立陣列

使用 ``np.array`` 從list來建立陣列:

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

和list不一樣，Numpy會限制所有在陣列中的內容須為相同型態。

如果型態不符合，Numpy會自動轉換其型態(如下面的浮點數+整數，會變成都是浮點數)

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

如果想要明確設定陣列的資料型態, 可以使用 ``dtype`` :

In [ ]:
np.array([1, 2, 3, 4], dtype='float32') # 32位浮點數

array([ 1.,  2.,  3.,  4.], dtype=float32)

不像Python的lists, NumPy陣列可以明確設定為多個維度，在此使用的包含list的list來初始化多維的Numpy維度:

In [ ]:
# nested 巢式 lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
np.array()

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

在內層的每一個list，會被當作是產出之結果二維陣列其中的每一列內容

## 從無到有建立陣列

在大型的陣列，使用程式從無到有建立Numpy陣列會更有效率

In [2]:
# 建立一個內容全為0，長度為10的整數陣列
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 建立一個內容全為1的3x5浮點數陣列
np.ones((3, 5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [5]:
# 建立一個填滿3.14內容的3x5陣列
x = np.full((3, 5), 3.14)
x

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [6]:
x[0,1]

3.14

In [20]:
# 建立一個依序填滿的陣列
# 從0開始，到20結束，每次以2為間隔
# (這和內建的range()函式類似)
np.arange(0, 20, 2, dtype = 'float')

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [ ]:
# 建立5個值的陣列，在0到1間 平均分佈
np.linspace(0, 1, 5)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

random 是 NumPy 庫中的一個模塊。該模塊包含用於生成隨機數的函數。該模塊包含一些簡單的隨機數據生成方法、一些排列和分布函數以及隨機生成器函數。

In [8]:
# 建立一個平均分佈的3x3陣列
# 在0到1之間亂數值
x = np.random.random((3, 3))
x

array([[0.45929926, 0.53975849, 0.9962341 ],
       [0.37836375, 0.82059175, 0.21747839],
       [0.82924524, 0.45508557, 0.64694999]])

In [9]:
x[0][1]

0.5397584855899772

In [10]:
x[1,2]

0.2174783918845109

In [11]:
# 建立一個3x3的陣列，內容為常態分佈的亂數值
# 平均是0而標準差是1
np.random.normal(0, 1, (3, 3))

array([[ 0.31028559,  1.38371386,  0.84335495],
       [ 0.41503347,  0.10010637,  0.06811616],
       [ 0.23884955, -0.34476523,  1.34921565]])

In [12]:
np.random.standard_normal((5,6))

array([[ 1.22536176,  0.32446728, -0.22650696,  0.21222892, -0.00461677,
        -0.76567679],
       [ 1.70102028, -0.82519851,  0.75465557,  0.04839682,  0.14356453,
        -0.01427694],
       [ 0.01087553, -1.26018157, -0.65525643,  0.39531887,  0.29209298,
        -0.56733202],
       [ 0.08270466,  1.4247205 ,  1.68262485, -0.98050882, -2.01906936,
        -0.37401609],
       [-0.01228533, -0.33801342,  0.06769269,  1.79215272, -0.82654818,
         0.05950837]])

In [13]:
# 建立一個3x3的陣列，內容為介於範圍是[0, 10]的整數亂數
np.random.randint(0, 10, (3, 3))

array([[4, 5, 0],
       [6, 5, 2],
       [5, 5, 8]])

In [18]:
np.random.randint(0,50,(4,4))

array([[10,  2, 28,  5],
       [42, 37, 15, 33],
       [32, 11, 41, 24],
       [39, 37, 46, 43]])

In [ ]:
# 建立一個3x3的 單位矩陣
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## Numpy的標準資料型態

標準的Numpy資料型態，可透過字串來指定型態:
```python
np.zeros(10, dtype='int16')
```

也可以使用相對應的Numpy物件來指定型態:
```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 